version: "3.5"
services:
  api1: &api # API - Instância 01
    image: node/rinha:latest
    hostname: api1
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.4GB"
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      POSTGRESQL_TRGM: true
      DB_MAX_CONNECTION: 200
      APP_PORT: 8081
    network_mode: host

  api2:
    <<: *api # API - Instância 02
    hostname: api2
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      POSTGRESQL_TRGM: true
      DB_MAX_CONNECTION: 200
      APP_PORT: 8082

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.7GB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      MAX_CONNECTIONS: 200
    network_mode: host
