version: "3.5"
services:
  api1: &api1 # API - Instância 01
    image: node/rinha:latest
    hostname: api1
    depends_on:
      - db

    expose:
      - 80
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      POSTGRESQL_TRGM: true
      APP_PORT: 80

  api2:
    <<: *api1
    hostname: api2

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5GB"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  default:
    driver: bridge
    name: rinha
